apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stellar-api.fullname" . }}
  labels: {{ include "stellar-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "stellar-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "stellar-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: {{ include "stellar-api.fullname" . }}-secrets
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          livenessProbe: {{ toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{ toYaml .Values.readinessProbe | nindent 12 }}
